# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50bdfa24932c646503b540e29eadea0e"
name = "Test Apps"
application_url = "https://customized-giving-pulled-trail.trycloudflare.com/"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,read_orders,read_content,write_content,read_online_store_navigation,write_online_store_navigation,write_app_proxy"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://customized-giving-pulled-trail.trycloudflare.com/authenticate"
]

[app_proxy]
url = "https://customized-giving-pulled-trail.trycloudflare.com"
subpath = "quick-order"
prefix = "apps"
