# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50bdfa24932c646503b540e29eadea0e"
name = "Test Apps"
application_url = "https://joey-unirrigated-normand.ngrok-free.dev/"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,read_inventory,read_locations,read_products,write_products,read_content,write_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://joey-unirrigated-normand.ngrok-free.dev/authenticate"
]
